CREATE TABLE [prod].[silver_casting_tree] (

	[versionnumber] varchar(50) NULL, 
	[entity_id] varchar(200) NULL, 
	[created_on] datetime2(6) NULL, 
	[modified_on] datetime2(6) NULL, 
	[casting_prod_order] varchar(8000) NULL, 
	[casting_tree_no] varchar(8000) NULL, 
	[casting_status] varchar(8000) NULL, 
	[master_alloy] varchar(8000) NULL, 
	[output_master_alloy_lot] varchar(8000) NULL, 
	[output_item] varchar(8000) NULL, 
	[output_item_dust] varchar(8000) NULL, 
	[output_item_spure] varchar(8000) NULL, 
	[output_item_weight] decimal(18,4) NULL, 
	[output_item_actual] decimal(18,4) NULL, 
	[output_item_dust_weight] decimal(18,4) NULL, 
	[output_item_spure_weight] decimal(18,4) NULL, 
	[scrap_item] varchar(8000) NULL, 
	[scrap_item_output_lot] varchar(8000) NULL, 
	[casting_to_warehouse] varchar(8000) NULL, 
	[casting_warehouse_lot] varchar(8000) NULL, 
	[warehouse_to_spure] varchar(8000) NULL, 
	[warehouse_to_spure_lot] varchar(8000) NULL, 
	[casting_output_status] int NULL, 
	[casting_stone_weight] decimal(18,4) NULL, 
	[casting_base_weight] decimal(18,4) NULL, 
	[casting_total_tree_weight] decimal(18,4) NULL, 
	[casting_net_wax_weight] decimal(18,4) NULL, 
	[casting_batch_no] varchar(8000) NULL, 
	[sink_modified_on] datetime2(6) NULL
);