CREATE TABLE [prod].[silver_production_status] (

	[versionnumber] varchar(50) NULL, 
	[entity_id] varchar(200) NULL, 
	[created_on] datetime2(6) NULL, 
	[modified_on] datetime2(6) NULL, 
	[prod_order_no] varchar(100) NULL, 
	[prod_order_line_no] varchar(100) NULL, 
	[job_sheet_no] varchar(100) NULL, 
	[type_name] varchar(200) NULL, 
	[prod_order_status] varchar(200) NULL, 
	[open] varchar(50) NULL, 
	[sales_order_no] varchar(100) NULL, 
	[current_location_code] varchar(100) NULL, 
	[past_location_code] varchar(100) NULL, 
	[employee_no] varchar(100) NULL, 
	[user_id] varchar(100) NULL, 
	[date_out] date NULL, 
	[quantity] decimal(18,2) NULL, 
	[date_in] date NULL, 
	[time_in] varchar(50) NULL, 
	[remaining_quantity] decimal(18,2) NULL, 
	[operation_no] varchar(100) NULL, 
	[item_no] varchar(100) NULL, 
	[entry_no_auto_no] varchar(100) NULL, 
	[antenna_id] varchar(100) NULL, 
	[rfid_code] varchar(200) NULL, 
	[rfid_transaction_name] varchar(200) NULL, 
	[qa_approved_name] varchar(200) NULL, 
	[machine_center_no] varchar(100) NULL, 
	[ingestion_ts] datetime2(6) NULL, 
	[sink_modified_on] datetime2(6) NULL
);