CREATE TABLE [prod].[silver_production_order_line] (

	[versionnumber] varchar(50) NULL, 
	[entity_id] varchar(200) NULL, 
	[created_on] datetime2(6) NULL, 
	[modified_on] datetime2(6) NULL, 
	[prod_order_no] varchar(8000) NULL, 
	[prod_line_status] varchar(8000) NULL, 
	[prod_order_line_no] bigint NULL, 
	[item_no] varchar(8000) NULL, 
	[prod_line_due_date] datetime2(6) NULL, 
	[item_description] varchar(8000) NULL, 
	[item_location] varchar(8000) NULL, 
	[prod_line_start_date] datetime2(6) NULL, 
	[prod_line_end_date] datetime2(6) NULL, 
	[item_uom] varchar(8000) NULL, 
	[prod_line_quantity] decimal(18,2) NULL, 
	[prod_line_finished_quantity] decimal(18,2) NULL, 
	[prod_line_remaining_quantity] decimal(18,2) NULL, 
	[sales_order_no] varchar(8000) NULL, 
	[sales_order_lineno] bigint NULL, 
	[item_material] varchar(8000) NULL, 
	[prod_line_unit_cost] decimal(18,2) NULL, 
	[item_routing_no] varchar(8000) NULL, 
	[item_routing_line] bigint NULL, 
	[bom_no] varchar(8000) NULL, 
	[bom_version] varchar(8000) NULL, 
	[item_routing_version] varchar(8000) NULL, 
	[prod_line_cost_amount] decimal(18,2) NULL, 
	[sink_modified_on] datetime2(6) NULL
);