CREATE TABLE [cx].[silver_sales_line] (

	[created_on] datetime2(6) NULL, 
	[modified_on] datetime2(6) NULL, 
	[sales_order_type] varchar(8000) NULL, 
	[customer_no] varchar(8000) NULL, 
	[sales_order_no] varchar(8000) NULL, 
	[sales_line_customer_noted] varchar(8000) NULL, 
	[sales_line_customer_remark] varchar(8000) NULL, 
	[sales_order_line_no] bigint NULL, 
	[item_no] varchar(8000) NULL, 
	[item_description] varchar(8000) NULL, 
	[item_reference] varchar(8000) NULL, 
	[item_quantity] decimal(18,2) NULL, 
	[item_quantity_shipped] decimal(18,2) NULL, 
	[item_quantity_invoiced] decimal(18,2) NULL, 
	[item_outstanding] decimal(18,2) NULL, 
	[item_quantity_to_ship] decimal(18,2) NULL, 
	[item_quantity_to_invoice] decimal(18,2) NULL, 
	[item_uom] varchar(8000) NULL, 
	[item_location] varchar(8000) NULL, 
	[item_posting_group] varchar(8000) NULL, 
	[sales_line_unit_price] decimal(18,2) NULL, 
	[item_unit_cost] decimal(18,2) NULL, 
	[sales_line_amount] decimal(18,2) NULL, 
	[sales_line_amount_VAT] decimal(18,2) NULL, 
	[sales_line_outstanding_amount] decimal(18,2) NULL, 
	[sales_line_requested_date] date NULL, 
	[sales_line_promised_date] date NULL, 
	[sales_line_plan_delivery] date NULL, 
	[sales_line_plan_shipment] date NULL, 
	[sales_order_shipment_date] date NULL, 
	[sales_order_currency] varchar(8000) NULL, 
	[item_material] varchar(8000) NULL
);