CREATE TABLE [cx].[silver_sales_header] (

	[created_on] datetime2(6) NULL, 
	[modified_on] datetime2(6) NULL, 
	[customer_no] varchar(8000) NULL, 
	[customer_name] varchar(8000) NULL, 
	[customer_initials] varchar(100) NULL, 
	[sales_order_type] varchar(8000) NULL, 
	[sales_order_no] varchar(8000) NULL, 
	[sales_order_status] varchar(8000) NULL, 
	[sales_order_released_date] date NULL, 
	[sales_order_document_date] date NULL, 
	[sales_order_posting_date] date NULL, 
	[sales_order_order_date] date NULL, 
	[sales_order_due_date] date NULL, 
	[sales_order_requested_date] date NULL, 
	[sales_order_promised_date] date NULL, 
	[sales_order_shipment_date] date NULL, 
	[sales_order_cs_reference] varchar(8000) NULL, 
	[cs_team] varchar(8000) NULL, 
	[cad_manager_team] varchar(8000) NULL, 
	[sales_order_currency] varchar(8000) NULL, 
	[ship_to_customer] varchar(8000) NULL, 
	[sales_order_external_document] varchar(8000) NULL, 
	[bill_to_customer] varchar(8000) NULL, 
	[sales_order_location] varchar(8000) NULL, 
	[item_material] varchar(8000) NULL, 
	[sales_order_amount_VAT] decimal(18,2) NULL, 
	[sales_order_amount] decimal(18,2) NULL
);